package com.labplatform.lab_platform_backend.repository;

import com.labplatform.lab_platform_backend.entity.Maintenance;
import com.labplatform.lab_platform_backend.entity.MaintenanceStatus;
import com.labplatform.lab_platform_backend.entity.MaintenanceType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

@Repository
public interface MaintenanceRepository extends JpaRepository<Maintenance, Long> {

    long countByStatus(MaintenanceStatus status);

    long countByEquipmentLaboratoryInstitutionIdAndStatus(Long institutionId, MaintenanceStatus status);

    long countByEquipmentLaboratoryInstitutionId(Long institutionId);

    List<Maintenance> findByEquipmentLaboratoryInstitutionId(Long institutionId);

    List<Maintenance> findByEquipmentLaboratoryInstitutionIdAndStatus(Long institutionId, MaintenanceStatus status);

    // --- Laboratory-Scoped Queries for LAB_MANAGER ---

    long countByEquipmentLaboratoryIdAndStatus(Long laboratoryId, MaintenanceStatus status);

    long countByEquipmentLaboratoryId(Long laboratoryId);

    List<Maintenance> findByEquipmentLaboratoryId(Long laboratoryId);

    List<Maintenance> findByEquipmentLaboratoryIdAndStatus(Long laboratoryId, MaintenanceStatus status);

    List<Maintenance> findByStatus(MaintenanceStatus status);

    List<Maintenance> findByTechnicianEmail(String email);

    List<Maintenance> findByEquipmentId(Long equipmentId);

    // --- Enterprise Analytics ---

    List<Maintenance> findByMaintenanceType(MaintenanceType maintenanceType);

    List<Maintenance> findByIsAutoGeneratedTrue();

    List<Maintenance> findByEquipmentIdOrderByMaintenanceDateDesc(Long equipmentId);

    Optional<Maintenance> findTopByEquipmentIdOrderByMaintenanceDateDesc(Long equipmentId);

    List<Maintenance> findByEquipmentIdAndStatus(Long equipmentId, MaintenanceStatus status);

    boolean existsByEquipmentIdAndStatusIn(Long equipmentId, List<MaintenanceStatus> statuses);

    // Upcoming maintenance (status PENDING, date >= today)
    @Query("SELECT m FROM Maintenance m WHERE m.status = 'PENDING' AND m.maintenanceDate >= :today ORDER BY m.maintenanceDate ASC")
    List<Maintenance> findUpcomingMaintenance(@Param("today") LocalDate today);

    @Query("SELECT m FROM Maintenance m WHERE m.status = 'PENDING' AND m.maintenanceDate >= :today AND m.equipment.laboratory.institution.id = :institutionId ORDER BY m.maintenanceDate ASC")
    List<Maintenance> findUpcomingMaintenanceByInstitution(@Param("today") LocalDate today, @Param("institutionId") Long institutionId);

    @Query("SELECT m FROM Maintenance m WHERE m.status = 'PENDING' AND m.maintenanceDate >= :today AND m.equipment.laboratory.id = :laboratoryId ORDER BY m.maintenanceDate ASC")
    List<Maintenance> findUpcomingMaintenanceByLaboratory(@Param("today") LocalDate today, @Param("laboratoryId") Long laboratoryId);

    // Overdue maintenance (status PENDING, date < today)
    @Query("SELECT m FROM Maintenance m WHERE m.status = 'PENDING' AND m.maintenanceDate < :today ORDER BY m.maintenanceDate ASC")
    List<Maintenance> findOverdueMaintenance(@Param("today") LocalDate today);

    @Query("SELECT m FROM Maintenance m WHERE m.status = 'PENDING' AND m.maintenanceDate < :today AND m.equipment.laboratory.institution.id = :institutionId ORDER BY m.maintenanceDate ASC")
    List<Maintenance> findOverdueMaintenanceByInstitution(@Param("today") LocalDate today, @Param("institutionId") Long institutionId);

    @Query("SELECT m FROM Maintenance m WHERE m.status = 'PENDING' AND m.maintenanceDate < :today AND m.equipment.laboratory.id = :laboratoryId ORDER BY m.maintenanceDate ASC")
    List<Maintenance> findOverdueMaintenanceByLaboratory(@Param("today") LocalDate today, @Param("laboratoryId") Long laboratoryId);

    // Total maintenance cost (COMPLETED)
    @Query("SELECT COALESCE(SUM(m.maintenanceCost), 0) FROM Maintenance m WHERE m.status = 'COMPLETED'")
    Double getTotalMaintenanceCost();

    @Query("SELECT COALESCE(SUM(m.maintenanceCost), 0) FROM Maintenance m WHERE m.status = 'COMPLETED' AND m.equipment.laboratory.institution.id = :institutionId")
    Double getTotalMaintenanceCostByInstitution(@Param("institutionId") Long institutionId);

    @Query("SELECT COALESCE(SUM(m.maintenanceCost), 0) FROM Maintenance m WHERE m.status = 'COMPLETED' AND m.equipment.laboratory.id = :laboratoryId")
    Double getTotalMaintenanceCostByLaboratory(@Param("laboratoryId") Long laboratoryId);
}