spring.application.name=lab-platform-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_platform_db
spring.datasource.username=your_database_username
spring.datasource.password=your_database_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=your_jwt_secret
jwt.expiration=86400000

spring.security.oauth2.client.registration.google.client-id=your_google_client_id
spring.security.oauth2.client.registration.google.client-secret=your_google_client_secret
spring.security.oauth2.client.registration.google.scope=email,profile

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authorization=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always