spring.application.name=lab-platform-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_platform_db
spring.datasource.username=USER_NAME
spring.datasource.password=USER_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=JWT_SECRET
jwt.expiration=86400000

spring.security.oauth2.client.registration.google.client-id=CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=CLIENT_PASSWORD
spring.security.oauth2.client.registration.google.scope=email,profile

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authorization=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always