import { useState } from "react";
import "./Table.css";

function MaintenanceTable({
  maintenanceRecords,
  startMaintenance,
  completeMaintenance,
  cancelMaintenance,
}) {

  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("ALL");

  const filteredRecords = maintenanceRecords.filter((record) => {
    const matchesSearch = record.equipment?.name
      ?.toLowerCase()
      .includes(search.toLowerCase());
    const matchesType =
      typeFilter === "ALL" || record.maintenanceType === typeFilter;
    return matchesSearch && matchesType;
  });

  const getStatusClass = (status) => {
    switch (status) {
      case "COMPLETED":
        return "status-approved";
      case "CANCELLED":
        return "status-rejected";
      case "IN_PROGRESS":
        return "status-processing";
      default:
        return "status-pending";
    }
  };

  const getTypeIcon = (type) => {
    switch (type) {
      case "PREVENTIVE":        return "🛡️";
      case "CORRECTIVE":        return "🔧";
      case "EMERGENCY":         return "🚨";
      case "CALIBRATION":       return "📐";
      case "SOFTWARE_UPDATE":   return "💻";
      case "HARDWARE_INSPECTION": return "🔍";
      default: return "🔧";
    }
  };

  return (

    <div className="table-card">

      <div className="table-header">

        <h2>Maintenance Records</h2>

        <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap" }}>

          <input
            type="text"
            className="table-search"
            placeholder="🔍 Search equipment..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />

          <select
            className="table-search"
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
            style={{ minWidth: "160px" }}
          >
            <option value="ALL">All Types</option>
            <option value="PREVENTIVE">🛡️ Preventive</option>
            <option value="CORRECTIVE">🔧 Corrective</option>
            <option value="EMERGENCY">🚨 Emergency</option>
            <option value="CALIBRATION">📐 Calibration</option>
            <option value="SOFTWARE_UPDATE">💻 Software Update</option>
            <option value="HARDWARE_INSPECTION">🔍 Hardware Inspection</option>
          </select>

        </div>

      </div>

      <table className="data-table">

        <thead>

          <tr>

            <th>ID</th>

            <th>Equipment</th>

            <th>Laboratory</th>

            <th>Type</th>

            <th>Technician</th>

            <th>Date</th>

            <th>Description</th>

            <th>Cost (₹)</th>

            <th>Auto</th>

            <th>Status</th>

            <th>Actions</th>

          </tr>

        </thead>

        <tbody>

          {filteredRecords.length > 0 ? (

            filteredRecords.map((record) => (

              <tr key={record.id}>

                <td>{record.id}</td>

                <td>{record.equipment?.name}</td>

                <td>{record.equipment?.laboratory?.name}</td>

                <td>
                  <span title={record.maintenanceType}>
                    {getTypeIcon(record.maintenanceType)}{" "}
                    <span style={{ fontSize: "0.75rem" }}>
                      {(record.maintenanceType || "PREVENTIVE")
                        .replace("_", " ")}
                    </span>
                  </span>
                </td>

                <td>{record.technician?.name || "-"}</td>

                <td>{record.maintenanceDate}</td>

                <td
                  style={{ maxWidth: "180px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}
                  title={record.description}
                >
                  {record.description}
                </td>

                <td>
                  {record.maintenanceCost != null
                    ? `₹${Number(record.maintenanceCost).toFixed(2)}`
                    : "-"}
                </td>

                <td>
                  {record.isAutoGenerated ? (
                    <span className="status-badge status-processing">Auto</span>
                  ) : (
                    <span style={{ color: "#64748b", fontSize: "0.8rem" }}>Manual</span>
                  )}
                </td>

                <td>

                  <span
                    className={`status-badge ${getStatusClass(record.status)}`}
                  >
                    {record.status}
                  </span>

                </td>

                <td>

                  {record.status === "PENDING" && (
                    <>
                      <button
                        className="action-btn approve-btn"
                        onClick={() => startMaintenance(record.id)}
                      >
                        ▶ Start
                      </button>

                      <button
                        className="action-btn reject-btn"
                        onClick={() => cancelMaintenance(record.id)}
                      >
                        ✖ Cancel
                      </button>
                    </>
                  )}

                  {record.status === "IN_PROGRESS" && (
                    <button
                      className="action-btn edit-btn"
                      onClick={() => completeMaintenance(record.id)}
                    >
                      ✔ Complete
                    </button>
                  )}

                  {(record.status === "COMPLETED" ||
                    record.status === "CANCELLED") && (
                    <button
                      className="action-btn complete-btn"
                      disabled
                    >
                      Processed
                    </button>
                  )}

                </td>

              </tr>

            ))

          ) : (

            <tr>

              <td
                colSpan="11"
                className="empty-table"
              >
                🔧 No maintenance records found.
              </td>

            </tr>

          )}

        </tbody>

      </table>

    </div>

  );

}

export default MaintenanceTable;