package com.labplatform.lab_platform_backend.service;

import com.labplatform.lab_platform_backend.dto.MaintenanceDashboardDTO;
import com.labplatform.lab_platform_backend.entity.*;
import com.labplatform.lab_platform_backend.repository.EquipmentCertificateRepository;
import com.labplatform.lab_platform_backend.repository.EquipmentRepository;
import com.labplatform.lab_platform_backend.repository.MaintenanceRepository;
import com.labplatform.lab_platform_backend.repository.UserRepository;
import com.labplatform.lab_platform_backend.util.SecurityUtil;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.List;

@Service
public class MaintenanceServiceImpl implements MaintenanceService {

    private final MaintenanceRepository maintenanceRepository;
    private final EquipmentRepository equipmentRepository;
    private final NotificationService notificationService;
    private final UserRepository userRepository;
    private final EquipmentCertificateRepository certificateRepository;
    private final SecurityUtil securityUtil;

    public MaintenanceServiceImpl(
            MaintenanceRepository maintenanceRepository,
            EquipmentRepository equipmentRepository,
            NotificationService notificationService,
            UserRepository userRepository,
            EquipmentCertificateRepository certificateRepository,
            SecurityUtil securityUtil) {

        this.maintenanceRepository = maintenanceRepository;
        this.equipmentRepository = equipmentRepository;
        this.notificationService = notificationService;
        this.userRepository = userRepository;
        this.certificateRepository = certificateRepository;
        this.securityUtil = securityUtil;
    }

    @Override
    public List<Maintenance> getAllMaintenanceRecords() {
        User user = securityUtil.getCurrentUser();
        if (securityUtil.isSystemAdmin(user)) {
            return maintenanceRepository.findAll();
        }
        if (user.getRole() == Role.LAB_MANAGER && user.getLaboratory() != null) {
            return maintenanceRepository.findByEquipmentLaboratoryId(user.getLaboratory().getId());
        }
        Long instId = securityUtil.getUserInstitutionId(user);
        if (instId == null) return List.of();
        return maintenanceRepository.findByEquipmentLaboratoryInstitutionId(instId);
    }

    @Override
    public Maintenance getMaintenanceById(Long id) {
        Maintenance maintenance = maintenanceRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Maintenance record not found with id: " + id));

        User user = securityUtil.getCurrentUser();
        if (!securityUtil.canViewMaintenance(user, maintenance)) {
            throw new AccessDeniedException("Access denied: You are not authorized to view this maintenance record");
        }
        return maintenance;
    }

    @Override
    public Maintenance createMaintenance(Maintenance maintenance) {

        Long equipmentId = maintenance.getEquipment().getId();

        Equipment equipment = equipmentRepository.findById(equipmentId)
                .orElseThrow(() -> new RuntimeException("Equipment not found"));

        User user = securityUtil.getCurrentUser();
        if (!securityUtil.canManageEquipment(user, equipment)) {
            throw new AccessDeniedException("Access denied: You cannot create maintenance requests for equipment belonging to another laboratory or institution");
        }

        maintenance.setEquipment(equipment);
        maintenance.setStatus(MaintenanceStatus.PENDING);

        if (maintenance.getMaintenanceType() == null) {
            maintenance.setMaintenanceType(MaintenanceType.PREVENTIVE);
        }

        if (maintenance.getIsAutoGenerated() == null) {
            maintenance.setIsAutoGenerated(false);
        }

        if (maintenance.getMaintenanceCost() == null) {
            maintenance.setMaintenanceCost(0.0);
        }

        // Hydrate assigned technician and trigger notification
        if (maintenance.getTechnician() != null && maintenance.getTechnician().getId() != null) {
            User tech = userRepository.findById(maintenance.getTechnician().getId()).orElse(null);

            if (tech != null && !securityUtil.isSameInstitution(tech, equipment)) {
                throw new AccessDeniedException("Access denied: Assigned technician does not belong to the equipment institution");
            }

            maintenance.setTechnician(tech);

            if (tech != null) {
                notificationService.createNotification(
                        tech,
                        "You have been assigned a new "
                                + maintenance.getMaintenanceType()
                                + " maintenance work order for "
                                + equipment.getName()
                                + " scheduled on " + maintenance.getMaintenanceDate() + "."
                );
            }
        }

        return maintenanceRepository.save(maintenance);
    }

    @Override
    public Maintenance updateMaintenance(Long id, Maintenance updatedMaintenance) {

        Maintenance maintenance = getMaintenanceById(id);

        User user = securityUtil.getCurrentUser();
        if (!securityUtil.canManageMaintenance(user, maintenance)) {
            throw new AccessDeniedException("Access denied: You cannot update maintenance records belonging to another laboratory or institution");
        }

        Equipment equipment = equipmentRepository.findById(
                        updatedMaintenance.getEquipment().getId())
                .orElseThrow(() -> new RuntimeException("Equipment not found"));

        if (!securityUtil.canManageEquipment(user, equipment)) {
            throw new AccessDeniedException("Access denied: Target equipment belongs to another laboratory or institution");
        }

        maintenance.setEquipment(equipment);
        maintenance.setMaintenanceDate(updatedMaintenance.getMaintenanceDate());
        maintenance.setDescription(updatedMaintenance.getDescription());

        // Notify technician if a new technician is assigned
        if (updatedMaintenance.getTechnician() != null && updatedMaintenance.getTechnician().getId() != null) {
            User tech = userRepository.findById(updatedMaintenance.getTechnician().getId()).orElse(null);

            if (tech != null && !securityUtil.isSameInstitution(tech, equipment)) {
                throw new AccessDeniedException("Access denied: Assigned technician does not belong to the equipment institution");
            }

            boolean isNewAssignment = maintenance.getTechnician() == null ||
                    !maintenance.getTechnician().getId().equals(tech != null ? tech.getId() : null);

            maintenance.setTechnician(tech);

            if (tech != null && isNewAssignment) {
                notificationService.createNotification(
                        tech,
                        "You have been assigned a maintenance work order for "
                                + equipment.getName()
                                + " scheduled on " + maintenance.getMaintenanceDate() + "."
                );
            }
        } else {
            maintenance.setTechnician(null);
        }

        if (updatedMaintenance.getMaintenanceType() != null) {
            maintenance.setMaintenanceType(updatedMaintenance.getMaintenanceType());
        }

        if (updatedMaintenance.getMaintenanceCost() != null) {
            maintenance.setMaintenanceCost(updatedMaintenance.getMaintenanceCost());
        }

        if (updatedMaintenance.getCompletionNotes() != null) {
            maintenance.setCompletionNotes(updatedMaintenance.getCompletionNotes());
        }

        return maintenanceRepository.save(maintenance);
    }

    @Override
    public Maintenance startMaintenance(Long id) {

        Maintenance maintenance = getMaintenanceById(id);

        User user = securityUtil.getCurrentUser();
        if (!securityUtil.canManageMaintenance(user, maintenance)) {
            throw new AccessDeniedException("Access denied: You cannot start maintenance for equipment belonging to another laboratory or institution");
        }

        maintenance.setStatus(MaintenanceStatus.IN_PROGRESS);

        Equipment equipment = maintenance.getEquipment();
        equipment.setStatus(EquipmentStatus.UNDER_MAINTENANCE);

        equipmentRepository.save(equipment);

        if (maintenance.getTechnician() != null) {
            notificationService.createNotification(
                    maintenance.getTechnician(),
                    "Maintenance started for "
                            + equipment.getName()
                            + ". Status updated to IN_PROGRESS."
            );
        }

        return maintenanceRepository.save(maintenance);
    }

    @Override
    public Maintenance completeMaintenance(Long id) {

        Maintenance maintenance = getMaintenanceById(id);

        User user = securityUtil.getCurrentUser();
        if (!securityUtil.canManageMaintenance(user, maintenance)) {
            throw new AccessDeniedException("Access denied: You cannot complete maintenance for equipment belonging to another laboratory or institution");
        }

        maintenance.setStatus(MaintenanceStatus.COMPLETED);

        Equipment equipment = maintenance.getEquipment();
        equipment.setStatus(EquipmentStatus.AVAILABLE);

        equipmentRepository.save(equipment);

        List<User> managers = userRepository.findByRole(Role.LAB_MANAGER);

        for (User manager : managers) {
            if (securityUtil.isSameInstitution(manager, equipment)) {
                notificationService.createNotification(
                        manager,
                        "Maintenance completed for "
                                + equipment.getName()
                                + ". Equipment is now AVAILABLE."
                );
            }
        }

        if (maintenance.getTechnician() != null) {
            notificationService.createNotification(
                    maintenance.getTechnician(),
                    "Maintenance completed for "
                            + equipment.getName()
                            + "."
            );
        }

        return maintenanceRepository.save(maintenance);
    }

    @Override
    public Maintenance cancelMaintenance(Long id) {

        Maintenance maintenance = getMaintenanceById(id);

        User user = securityUtil.getCurrentUser();
        if (!securityUtil.canManageMaintenance(user, maintenance)) {
            throw new AccessDeniedException("Access denied: You cannot cancel maintenance for equipment belonging to another laboratory or institution");
        }

        maintenance.setStatus(MaintenanceStatus.CANCELLED);

        Equipment equipment = maintenance.getEquipment();
        equipment.setStatus(EquipmentStatus.AVAILABLE);

        equipmentRepository.save(equipment);

        if (maintenance.getTechnician() != null) {
            notificationService.createNotification(
                    maintenance.getTechnician(),
                    "Maintenance work order for "
                            + equipment.getName()
                            + " has been cancelled."
            );
        }

        return maintenanceRepository.save(maintenance);
    }

    @Override
    public List<Maintenance> getPendingMaintenance() {
        User user = securityUtil.getCurrentUser();
        if (securityUtil.isSystemAdmin(user)) {
            return maintenanceRepository.findByStatus(MaintenanceStatus.PENDING);
        }
        if (user.getRole() == Role.LAB_MANAGER && user.getLaboratory() != null) {
            return maintenanceRepository.findByEquipmentLaboratoryIdAndStatus(user.getLaboratory().getId(), MaintenanceStatus.PENDING);
        }
        Long instId = securityUtil.getUserInstitutionId(user);
        if (instId == null) return List.of();
        return maintenanceRepository.findByEquipmentLaboratoryInstitutionIdAndStatus(instId, MaintenanceStatus.PENDING);
    }

    @Override
    public List<Maintenance> getMyMaintenance(String technicianEmail) {
        return maintenanceRepository.findByTechnicianEmail(technicianEmail);
    }

    @Override
    public void deleteMaintenance(Long id) {

        Maintenance maintenance = getMaintenanceById(id);

        User user = securityUtil.getCurrentUser();
        if (!securityUtil.canManageMaintenance(user, maintenance)) {
            throw new AccessDeniedException("Access denied: You cannot delete maintenance records belonging to another laboratory or institution");
        }

        maintenanceRepository.delete(maintenance);
    }

    @Override
    public MaintenanceDashboardDTO getMaintenanceDashboard() {

        User user = securityUtil.getCurrentUser();
        LocalDate today = LocalDate.now();

        MaintenanceDashboardDTO dashboard = new MaintenanceDashboardDTO();

        if (securityUtil.isSystemAdmin(user)) {
            List<Maintenance> upcoming = maintenanceRepository.findUpcomingMaintenance(today);
            List<Maintenance> overdue  = maintenanceRepository.findOverdueMaintenance(today);

            dashboard.setUpcomingMaintenanceCount(upcoming.size());
            dashboard.setOverdueMaintenance(overdue);
            dashboard.setOverdueMaintenanceCount(overdue.size());
            dashboard.setUpcomingMaintenance(upcoming.stream().limit(10).toList());

            dashboard.setTotalMaintenanceCount(maintenanceRepository.count());
            dashboard.setCompletedMaintenanceCount(
                    maintenanceRepository.countByStatus(MaintenanceStatus.COMPLETED));
            dashboard.setPendingMaintenanceCount(
                    maintenanceRepository.countByStatus(MaintenanceStatus.PENDING));
            dashboard.setInProgressMaintenanceCount(
                    maintenanceRepository.countByStatus(MaintenanceStatus.IN_PROGRESS));

            Double cost = maintenanceRepository.getTotalMaintenanceCost();
            dashboard.setTotalMaintenanceCost(cost != null ? cost : 0.0);

            dashboard.setCertificatesExpiringCount(
                    certificateRepository.countByStatus(CertificateStatus.EXPIRING_SOON));
            dashboard.setExpiredCertificatesCount(
                    certificateRepository.countByStatus(CertificateStatus.EXPIRED));

            LocalDate in30 = today.plusDays(30);
            dashboard.setExpiringCertificates(
                    certificateRepository.findByExpiryDateBetween(today, in30));

            return dashboard;
        }

        if (user.getRole() == Role.LAB_MANAGER && user.getLaboratory() != null) {
            Long labId = user.getLaboratory().getId();

            List<Maintenance> upcoming = maintenanceRepository.findUpcomingMaintenanceByLaboratory(today, labId);
            List<Maintenance> overdue  = maintenanceRepository.findOverdueMaintenanceByLaboratory(today, labId);

            dashboard.setUpcomingMaintenanceCount(upcoming.size());
            dashboard.setOverdueMaintenance(overdue);
            dashboard.setOverdueMaintenanceCount(overdue.size());
            dashboard.setUpcomingMaintenance(upcoming.stream().limit(10).toList());

            dashboard.setTotalMaintenanceCount(maintenanceRepository.countByEquipmentLaboratoryId(labId));
            dashboard.setCompletedMaintenanceCount(
                    maintenanceRepository.countByEquipmentLaboratoryIdAndStatus(labId, MaintenanceStatus.COMPLETED));
            dashboard.setPendingMaintenanceCount(
                    maintenanceRepository.countByEquipmentLaboratoryIdAndStatus(labId, MaintenanceStatus.PENDING));
            dashboard.setInProgressMaintenanceCount(
                    maintenanceRepository.countByEquipmentLaboratoryIdAndStatus(labId, MaintenanceStatus.IN_PROGRESS));

            Double cost = maintenanceRepository.getTotalMaintenanceCostByLaboratory(labId);
            dashboard.setTotalMaintenanceCost(cost != null ? cost : 0.0);

            dashboard.setCertificatesExpiringCount(
                    certificateRepository.countByEquipmentLaboratoryIdAndStatus(labId, CertificateStatus.EXPIRING_SOON));
            dashboard.setExpiredCertificatesCount(
                    certificateRepository.countByEquipmentLaboratoryIdAndStatus(labId, CertificateStatus.EXPIRED));

            LocalDate in30 = today.plusDays(30);
            dashboard.setExpiringCertificates(
                    certificateRepository.findByEquipmentLaboratoryIdAndExpiryDateBetween(labId, today, in30));

            return dashboard;
        }

        Long instId = securityUtil.getUserInstitutionId(user);
        if (instId == null) {
            return dashboard;
        }

        List<Maintenance> upcoming = maintenanceRepository.findUpcomingMaintenanceByInstitution(today, instId);
        List<Maintenance> overdue  = maintenanceRepository.findOverdueMaintenanceByInstitution(today, instId);

        dashboard.setUpcomingMaintenanceCount(upcoming.size());
        dashboard.setOverdueMaintenance(overdue);
        dashboard.setOverdueMaintenanceCount(overdue.size());
        dashboard.setUpcomingMaintenance(upcoming.stream().limit(10).toList());

        dashboard.setTotalMaintenanceCount(maintenanceRepository.countByEquipmentLaboratoryInstitutionId(instId));
        dashboard.setCompletedMaintenanceCount(
                maintenanceRepository.countByEquipmentLaboratoryInstitutionIdAndStatus(instId, MaintenanceStatus.COMPLETED));
        dashboard.setPendingMaintenanceCount(
                maintenanceRepository.countByEquipmentLaboratoryInstitutionIdAndStatus(instId, MaintenanceStatus.PENDING));
        dashboard.setInProgressMaintenanceCount(
                maintenanceRepository.countByEquipmentLaboratoryInstitutionIdAndStatus(instId, MaintenanceStatus.IN_PROGRESS));

        Double cost = maintenanceRepository.getTotalMaintenanceCostByInstitution(instId);
        dashboard.setTotalMaintenanceCost(cost != null ? cost : 0.0);

        dashboard.setCertificatesExpiringCount(
                certificateRepository.countByEquipmentLaboratoryInstitutionIdAndStatus(instId, CertificateStatus.EXPIRING_SOON));
        dashboard.setExpiredCertificatesCount(
                certificateRepository.countByEquipmentLaboratoryInstitutionIdAndStatus(instId, CertificateStatus.EXPIRED));

        LocalDate in30 = today.plusDays(30);
        dashboard.setExpiringCertificates(
                certificateRepository.findByEquipmentLaboratoryInstitutionIdAndExpiryDateBetween(instId, today, in30));

        return dashboard;
    }
}