package com.labplatform.lab_platform_backend.service;

import com.labplatform.lab_platform_backend.entity.*;
import com.labplatform.lab_platform_backend.repository.*;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

@Service
public class PreventiveMaintenanceServiceImpl implements PreventiveMaintenanceService {

    // Maintenance interval thresholds in days
    private static final int HIGH_UTILIZATION_INTERVAL   = 15;
    private static final int MEDIUM_UTILIZATION_INTERVAL = 20;
    private static final int LOW_UTILIZATION_INTERVAL    = 30;

    private final EquipmentRepository equipmentRepository;
    private final EquipmentUtilizationStatsRepository statsRepository;
    private final MaintenanceRepository maintenanceRepository;
    private final UserRepository userRepository;
    private final NotificationService notificationService;

    public PreventiveMaintenanceServiceImpl(
            EquipmentRepository equipmentRepository,
            EquipmentUtilizationStatsRepository statsRepository,
            MaintenanceRepository maintenanceRepository,
            UserRepository userRepository,
            NotificationService notificationService) {

        this.equipmentRepository = equipmentRepository;
        this.statsRepository = statsRepository;
        this.maintenanceRepository = maintenanceRepository;
        this.userRepository = userRepository;
        this.notificationService = notificationService;
    }

    @Override
    public void generateMaintenanceSchedules() {

        List<Equipment> allEquipment = equipmentRepository.findAll();

        for (Equipment equipment : allEquipment) {

            // Skip equipment already UNDER_MAINTENANCE or OUT_OF_SERVICE
            if (equipment.getStatus() == EquipmentStatus.UNDER_MAINTENANCE
                    || equipment.getStatus() == EquipmentStatus.OUT_OF_SERVICE
                    || equipment.getStatus() == EquipmentStatus.RETIRED) {
                continue;
            }

            // Skip if there is already a PENDING or IN_PROGRESS maintenance task
            boolean hasActive = maintenanceRepository.existsByEquipmentIdAndStatusIn(
                    equipment.getId(),
                    Arrays.asList(MaintenanceStatus.PENDING, MaintenanceStatus.IN_PROGRESS)
            );

            if (hasActive) {
                continue;
            }

            // Determine maintenance interval from utilization tier
            int intervalDays = resolveInterval(equipment.getId());

            // Find last maintenance date
            Optional<Maintenance> lastMaintenance = maintenanceRepository
                    .findTopByEquipmentIdOrderByMaintenanceDateDesc(equipment.getId());

            LocalDate referenceDate = lastMaintenance
                    .map(Maintenance::getMaintenanceDate)
                    .orElse(LocalDate.now().minusDays(intervalDays)); // treat as never maintained

            LocalDate nextDueDate = referenceDate.plusDays(intervalDays);

            // If next due date is today or in the past, generate a work order
            if (!nextDueDate.isAfter(LocalDate.now())) {

                Maintenance maintenance = new Maintenance();
                maintenance.setEquipment(equipment);
                maintenance.setMaintenanceDate(LocalDate.now().plusDays(1)); // schedule for tomorrow
                maintenance.setDescription("Auto-generated preventive maintenance based on utilization schedule. "
                        + "Interval: " + intervalDays + " days.");
                maintenance.setStatus(MaintenanceStatus.PENDING);
                maintenance.setMaintenanceType(MaintenanceType.PREVENTIVE);
                maintenance.setIsAutoGenerated(true);
                maintenance.setMaintenanceCost(0.0);

                maintenanceRepository.save(maintenance);

                // Notify lab managers
                List<User> managers = userRepository.findByRole(Role.LAB_MANAGER);
                for (User manager : managers) {
                    notificationService.createNotification(
                            manager,
                            "🔧 Preventive maintenance auto-scheduled for '"
                                    + equipment.getName() + "'. Due: " + maintenance.getMaintenanceDate()
                    );
                }
            }
        }
    }

    @Override
    public void checkAndNotifyMaintenanceDue() {

        LocalDate today = LocalDate.now();

        List<User> managers  = userRepository.findByRole(Role.LAB_MANAGER);
        List<User> admins    = userRepository.findByRole(Role.INSTITUTION_ADMIN);
        List<User> sysAdmins = userRepository.findByRole(Role.SYSTEM_ADMIN);

        // Overdue maintenance (status PENDING, date already past)
        List<Maintenance> overdue = maintenanceRepository.findOverdueMaintenance(today);

        for (Maintenance m : overdue) {
            String msg = "🚨 OVERDUE MAINTENANCE: '"
                    + m.getEquipment().getName()
                    + "' had maintenance scheduled on " + m.getMaintenanceDate()
                    + " but it has not been started. Please take action immediately.";
            for (User u : managers)  notificationService.createNotification(u, msg);
            for (User u : admins)    notificationService.createNotification(u, msg);
            for (User u : sysAdmins) notificationService.createNotification(u, msg);
        }

        // Upcoming maintenance (due within 3 days)
        List<Maintenance> upcoming = maintenanceRepository.findUpcomingMaintenance(today);
        for (Maintenance m : upcoming) {
            if (!m.getMaintenanceDate().isAfter(today.plusDays(3))) {
                String msg = "📅 Upcoming maintenance for '"
                        + m.getEquipment().getName()
                        + "' is scheduled on " + m.getMaintenanceDate() + ".";
                for (User u : managers) notificationService.createNotification(u, msg);
            }
        }
    }

    private int resolveInterval(Long equipmentId) {
        return statsRepository.findByEquipmentId(equipmentId)
                .map(stats -> {
                    double pct = stats.getUtilizationPercentage();
                    if (pct >= 70) return HIGH_UTILIZATION_INTERVAL;
                    if (pct >= 30) return MEDIUM_UTILIZATION_INTERVAL;
                    return LOW_UTILIZATION_INTERVAL;
                })
                .orElse(LOW_UTILIZATION_INTERVAL); // default for new/unanalyzed equipment
    }
}
