import { useEffect, useState } from "react";
import { toast } from "react-toastify";
import Layout from "../components/Layout";
import api from "../api/axios";
import MaintenanceForm from "../components/MaintenanceForm";
import MaintenanceTable from "../components/MaintenanceTable";
import DashboardCard from "../components/DashboardCard";
import {
  FaTools,
  FaExclamationTriangle,
  FaCertificate,
  FaRupeeSign,
  FaCalendarAlt,
  FaCalendarPlus,
  FaCheckCircle,
  FaClock
} from "react-icons/fa";

function MaintenancePage() {

  const [maintenanceRecords, setMaintenanceRecords] = useState([]);
  const [equipmentList, setEquipmentList] = useState([]);
  const [technicians, setTechnicians] = useState([]);
  const [dashboard, setDashboard] = useState(null);
  const [certAlerts, setCertAlerts] = useState([]);

  const [formData, setFormData] = useState({
    equipmentId: "",
    technicianId: "",
    maintenanceDate: "",
    description: "",
    maintenanceType: "PREVENTIVE",
    maintenanceCost: "",
  });

  useEffect(() => {
    loadMaintenance();
    loadEquipment();
    loadTechnicians();
    loadDashboard();
    loadCertAlerts();
  }, []);

  const loadMaintenance = async () => {
    try {
      const response = await api.get("/maintenance");
      setMaintenanceRecords(response.data);
    } catch (error) {
      console.error(error);
      toast.error("Failed to load maintenance records.");
    }
  };

  const loadEquipment = async () => {
    try {
      const response = await api.get("/equipment");
      setEquipmentList(response.data);
    } catch (error) {
      console.error(error);
    }
  };

  const loadTechnicians = async () => {
    try {
      const response = await api.get("/users");
      const techs = response.data.filter(
        user => user.role === "LAB_TECHNICIAN"
      );
      setTechnicians(techs);
    } catch (error) {
      console.error(error);
    }
  };

  const loadDashboard = async () => {
    try {
      const response = await api.get("/maintenance/dashboard");
      setDashboard(response.data);
    } catch (error) {
      console.warn("Maintenance dashboard not available:", error);
    }
  };

  const loadCertAlerts = async () => {
    try {
      const response = await api.get("/certificates/alerts");
      setCertAlerts(response.data || []);
    } catch (error) {
      console.warn("Failed to load certificate alerts:", error);
    }
  };

  const handleChange = e => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleScheduleRenewal = (alert) => {
    if (alert.hasOpenMaintenance) {
      toast.info(`Active maintenance work order already exists for ${alert.equipmentName}.`);
      return;
    }

    const todayStr = new Date().toISOString().split("T")[0];
    setFormData({
      equipmentId: String(alert.equipmentId),
      technicianId: "",
      maintenanceDate: todayStr,
      description: `Calibration & Certificate Renewal: ${alert.certificateName} (Cert No: ${alert.certificateNumber || "N/A"})`,
      maintenanceType: "CALIBRATION",
      maintenanceCost: "",
    });

    toast.success(`Pre-filled calibration renewal form for ${alert.equipmentName}.`);

    const formElement = document.querySelector(".form-card");
    if (formElement) {
      formElement.scrollIntoView({ behavior: "smooth" });
    }
  };

  const handleSubmit = async e => {
    e.preventDefault();
    try {
      await api.post("/maintenance", {
        equipment: {
          id: formData.equipmentId
        },
        technician: formData.technicianId
          ? { id: formData.technicianId }
          : null,
        maintenanceDate: formData.maintenanceDate,
        description: formData.description,
        maintenanceType: formData.maintenanceType || "PREVENTIVE",
        maintenanceCost: formData.maintenanceCost
          ? parseFloat(formData.maintenanceCost)
          : 0.0,
        isAutoGenerated: false,
      });

      toast.success("Maintenance request created.");

      setFormData({
        equipmentId: "",
        technicianId: "",
        maintenanceDate: "",
        description: "",
        maintenanceType: "PREVENTIVE",
        maintenanceCost: "",
      });

      loadMaintenance();
      loadDashboard();
      loadCertAlerts();
    } catch (error) {
      console.error(error);
      toast.error("Failed to create maintenance.");
    }
  };

  const startMaintenance = async id => {
    try {
      await api.put(`/maintenance/${id}/start`);
      toast.success("Maintenance started.");
      loadMaintenance();
      loadDashboard();
      loadCertAlerts();
    } catch (error) {
      console.error(error);
      toast.error("Failed to start maintenance.");
    }
  };

  const completeMaintenance = async id => {
    try {
      await api.put(`/maintenance/${id}/complete`);
      toast.success("Maintenance completed.");
      loadMaintenance();
      loadDashboard();
      loadCertAlerts();
    } catch (error) {
      console.error(error);
      toast.error("Failed to complete maintenance.");
    }
  };

  const cancelMaintenance = async id => {
    try {
      await api.put(`/maintenance/${id}/cancel`);
      toast.success("Maintenance cancelled.");
      loadMaintenance();
      loadDashboard();
      loadCertAlerts();
    } catch (error) {
      console.error(error);
      toast.error("Failed to cancel maintenance.");
    }
  };

  const stats = {
    total: maintenanceRecords.length,
    pending: maintenanceRecords.filter(m => m.status === "PENDING").length,
    progress: maintenanceRecords.filter(m => m.status === "IN_PROGRESS").length,
    completed: maintenanceRecords.filter(m => m.status === "COMPLETED").length
  };

  return (
    <Layout>
      <div className="equipment-page">
        <div className="page-header">
          <div>
            <h1>
              <FaTools />
              Maintenance &amp; Asset Service Management
            </h1>
            <p>
              Schedule work orders, assign technicians, track servicing schedules, and log costs.
            </p>
          </div>
        </div>

        {/* Primary Operational Stats */}
        <div className="dashboard-container">
          <DashboardCard
            title="Total Records"
            value={stats.total}
            icon={<FaTools />}
          />

          <DashboardCard
            title="Pending Servicing"
            value={stats.pending}
            icon={<FaCalendarAlt />}
          />

          <DashboardCard
            title="In Progress"
            value={stats.progress}
            icon={<FaTools />}
          />

          <DashboardCard
            title="Completed"
            value={stats.completed}
            icon={<FaTools />}
          />
        </div>

        {/* Enterprise Dashboard Cards */}
        {dashboard && (
          <>
            <h2 className="dashboard-section-title">
              <FaTools style={{ color: "var(--color-primary)" }} /> Executive Maintenance Metrics
            </h2>

            <div className="dashboard-container">
              <DashboardCard
                title="Upcoming Work Orders"
                value={dashboard.upcomingMaintenanceCount}
                icon={<FaCalendarAlt />}
              />

              <DashboardCard
                title="Overdue Servicing"
                value={dashboard.overdueMaintenanceCount}
                icon={<FaExclamationTriangle />}
              />

              <DashboardCard
                title="Certs Expiring (30d)"
                value={dashboard.certificatesExpiringCount}
                icon={<FaCertificate />}
              />

              <DashboardCard
                title="Expired Certifications"
                value={dashboard.expiredCertificatesCount}
                icon={<FaCertificate />}
              />

              <DashboardCard
                title="Total Service Cost"
                value={`₹${Number(dashboard.totalMaintenanceCost || 0).toFixed(0)}`}
                icon={<FaRupeeSign />}
              />
            </div>

            {/* Overdue Maintenance Banner Alert */}
            {dashboard.overdueMaintenance && dashboard.overdueMaintenance.length > 0 && (
              <div style={{
                background: "var(--color-danger-bg)",
                border: "1px solid rgba(220, 38, 38, 0.3)",
                borderRadius: "var(--radius-lg)",
                padding: "20px",
                marginBottom: "24px",
              }}>
                <h3 style={{ color: "var(--color-danger)", margin: "0 0 12px 0", fontSize: "15px", fontWeight: 700, display: "flex", alignItems: "center", gap: "8px" }}>
                  <FaExclamationTriangle /> Overdue Servicing Work Orders ({dashboard.overdueMaintenance.length})
                </h3>
                {dashboard.overdueMaintenance.map((m) => (
                  <div key={m.id} style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    padding: "8px 0",
                    borderBottom: "1px solid rgba(220, 38, 38, 0.15)",
                    fontSize: "13px",
                  }}>
                    <span style={{ fontWeight: 600, color: "var(--color-text-main)" }}>
                      {m.equipment?.name} ({m.maintenanceType || "PREVENTIVE"})
                    </span>
                    <span style={{ color: "var(--color-danger)", fontWeight: 700 }}>
                      Due Date: {m.maintenanceDate}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </>
        )}

        {/* Certificate & Calibration Alerts Section */}
        {certAlerts && certAlerts.length > 0 && (
          <div style={{
            background: "var(--color-bg-card)",
            border: "1px solid var(--color-border)",
            borderRadius: "var(--radius-lg)",
            padding: "20px",
            marginBottom: "24px",
            boxShadow: "var(--shadow-sm)"
          }}>
            <h3 style={{ margin: "0 0 14px 0", fontSize: "15px", fontWeight: 700, color: "var(--color-primary)", display: "flex", alignItems: "center", gap: "8px" }}>
              <FaCertificate style={{ color: "#eab308" }} /> Certificate &amp; Calibration Alerts ({certAlerts.length})
            </h3>

            <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
              {certAlerts.map((alert) => {
                const isExpired = alert.status === "EXPIRED";
                return (
                  <div
                    key={alert.id}
                    style={{
                      padding: "12px 16px",
                      background: isExpired ? "var(--color-danger-bg)" : "var(--color-warning-bg)",
                      border: `1px solid ${isExpired ? "rgba(220, 38, 38, 0.3)" : "rgba(217, 119, 6, 0.3)"}`,
                      borderRadius: "var(--radius-md)",
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      gap: "16px",
                      flexWrap: "wrap"
                    }}
                  >
                    <div style={{ flex: 1, minWidth: "260px" }}>
                      <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "4px" }}>
                        <span style={{ fontWeight: 700, fontSize: "14px", color: "var(--color-text-main)" }}>
                          {alert.equipmentName}
                        </span>
                        <span className={`status-badge status-${isExpired ? "rejected" : "pending"}`}>
                          {alert.status?.replaceAll("_", " ")}
                        </span>
                        {alert.isMandatory && (
                          <span style={{ fontSize: "11px", fontWeight: 700, color: "var(--color-danger)", background: "rgba(220,38,38,0.1)", padding: "2px 6px", borderRadius: "4px" }}>
                            Mandatory
                          </span>
                        )}
                      </div>

                      <div style={{ fontSize: "12.5px", color: "var(--color-text-subtle)", display: "flex", gap: "14px", flexWrap: "wrap" }}>
                        <span><strong>Certificate:</strong> {alert.certificateName} ({alert.certificateNumber || "N/A"})</span>
                        <span style={{ color: isExpired ? "var(--color-danger)" : "var(--color-warning)", fontWeight: 700 }}>
                          <FaClock style={{ marginRight: "4px" }} /> {alert.remainingText}
                        </span>
                      </div>
                    </div>

                    <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
                      {alert.hasOpenMaintenance ? (
                        <span style={{ fontSize: "12px", color: "var(--color-success)", fontWeight: 600, display: "inline-flex", alignItems: "center", gap: "4px" }}>
                          <FaCheckCircle /> Maintenance Scheduled
                        </span>
                      ) : (
                        <button
                          className="action-btn approve-btn"
                          onClick={() => handleScheduleRenewal(alert)}
                          style={{ fontSize: "12.5px", padding: "8px 14px" }}
                        >
                          <FaCalendarPlus /> Schedule Renewal
                        </button>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        <MaintenanceForm
          equipmentList={equipmentList}
          technicians={technicians}
          formData={formData}
          handleChange={handleChange}
          handleSubmit={handleSubmit}
        />

        <MaintenanceTable
          maintenanceRecords={maintenanceRecords}
          startMaintenance={startMaintenance}
          completeMaintenance={completeMaintenance}
          cancelMaintenance={cancelMaintenance}
        />

      </div>
    </Layout>
  );
}

export default MaintenancePage;